#!/usr/bin/env php
<?php
require_once __DIR__ . '/src/Autoloader.php';

App\Autoloader::register();

$kernel = new App\Kernel($argv, $argc);

$kernel
	->addCommand('csv2Json', \App\Command\Csv2JsonCommand::class)
    ->addArgument('file',true, true, 'Fichier csv a transformer en json')
	->addOption('fields', true, false, 'Liste des champs présent dans le Json')
	->addOption('aggregate')
	->addOption('desc', true, false)
    ->addOption('pretty', false);

$kernel->addCommand('unit-test', [\App\Test\Test::class, 'run']);

$kernel->run();
